New analysis
openforcefield/openff-benchmark pull request #86
Opened 2021-06-14 19:48 UTC by ldamore

## Description
This PR introduces two additional benchmark analysis proposed by B. Swope and X. Lucas.

## Installation of `new_analysis` command group in a dev environment

First, follow the installation procedures for the `openff-benchmark-optimization` environment described in [Deployment Procedure document](https://openforcefield.atlassian.net/wiki/spaces/PS/pages/873922575/Deployment+Procedure#Installation)

Once this is done, you can clone the environment into a development environment:

```
conda create -n openff-analysis --clone openff-benchmark-optimization
conda activate openff-analysis
```

Install the `new_analysis` branch from github:

```
git clone https://github.com/openforcefield/openff-benchmark
cd openff-benchmark
git checkout --track origin/new_analysis
pip install -e .
```

## General comments
The two new analysis are typically executed at *point (5)* of the [Optimization Benchmark Protocol](https://openforcefield.atlassian.net/wiki/spaces/PS/pages/971898891/Optimization+Benchmarking+Protocol+-+Season+1)

With `openff-benchmark report bill` the analysis proposed by B. Swope is executed. The command accepts the paths of the optimized molecules obtained from the optimization step. Additionally, the reference method (b3lyp-d3bj by default) and an output directory can be specified.

  `openff-benchmark report bill --input-path 4-compute-qm-filtered --input-path 4-compute-mm-filtered --ref-method b3lyp-d3bj  --output-directory 5-results-bill`

The command creates one output csv file per method, which are named `bill_<method>.csv`, i.e. `bill_openff-1.0.0.csv`

The analysis proposed by B. Swope operates as follows:

- For each molecule MOL-00001-XX.sdf

  - Report the relative energy (**dE**) of each MM optimized conformer (**MM_conf**) with respect to the MM optimized conformer which is the global minimum (**MM_min**)

  - **dE = E<sub>MM_conf</sub> - E<sub>MM_min</sub>**

  - Report the RMSD between each **MM_conf** and the QM optimized conformer which is the global minimum (**QM_min**)

  - **RMSD (MM_conf | QM_min)**

With `openff-benchmark report xavier` the analysis proposed by X. Lucas is executed. The command accepts the paths of the optimized molecules obtained from the optimization step. Additionally, the reference method (b3lyp-d3bj by default) and an output directory can be specified.

`openff-benchmark report xavier --input-path 4-compute-qm-filtered --input-path 4-compute-mm-filtered --ref-method b3lyp-d3bj --output-directory 5-results-xavier`

The command creates one output csv file per method, which are named `xavier_<method>.csv`, i.e. `xavier_openff-1.0.0.csv`

The analysis proposed by X. Lucas operates as follows:

- For each molecule MOL-00001-XX.sdf

  - Find the MM reference conformer (**MM_ref**) with the lowest RMSD with respect to **QM_min**

  - Report the relative energy (**dE**) and RMSD between **MM_ref** and **MM_min**

  - **dE = E<sub>MM_ref</sub> - E<sub>MM_min</sub>**

  - **RMSD (MM_ref | MM_min)**

The final `openff-benchmark report plots-bill` and `openff-benchmark report plots-xavier` commands take the directories containing the csv files as an input (output of `5-results-bill` or `5-results-xavier`).

For `5-results-bill` an `rmsd-cutoff` and `de-cutoff` should be set. 

`openff-benchmark report plots-bill --input-path 5-results-bill/ --ref-method bill_gaff-2.11 --de-cutoff 1.5 --rmsd-cutoff 1.0 `

The algorithm will generate a ridge plot of all the conformers within the rmsd-cutoff for a range of dE values, and another ridge plot of all the conformers within the de-cutoff for a range of rsmd values.

For `5-results-xavier`

`openff-benchmark report plots-xavier --input-path 5-results-xavier/ --ref-method xavier_gaff-2.11`

The algorithm will generate similar plots as for `compare-forcefields` and `match_minima`

### Please note
When generating plots, `--ref-method` is used _**for indexing purposes only**_. Hence, one could arbitrarly use any .*csv generated by the corresponding analysis. `b3lyp-d3bj` has been omitted in the analysis for the sake of computational time and cannot therefore be used for indexing.

## Todos

  - [ ] Fix an error that prevent the drawing of density plots when using the intersection of methods at the plotting stage.
  - [ ] Fix overlapping ytics labels in ridge plots
  - [x]  Introduced the intersection of methods at the plotting stage. 

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

2021-06-15 00:03 UTC, dotsdl commented
Awesome, thanks @ldamore! Reviewing!

2021-07-15 02:32 UTC, dotsdl requested changes
Thank you @ldamore for putting this together! I have added inline comments that should be addressed before we proceed to merge. Happy to assist with any of these live as well!

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/analysis/new_draw.py
> +    global results
Remove use of `global`. Shouldn't be necessary and we really don't want global state on the module.

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/analysis/new_draw.py
> +#            )
Remove if not needed.

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/analysis/new_draw.py
> +            # z_range=(-260,5200),
Remove if not needed.

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/analysis/new_draw.py
> +    #df = pd.concat(temp, ignore_index=True)
Remove if not needed.

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/analysis/new_draw.py
> +    # Define and use a simple function to label the plot in axes coordinates
Can you add a docstring indicating how this function differs from `draw.draw_ridge`?

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/analysis/new_draw.py
> +    # ax.set_yticks([0.4])
Remove if not needed.

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/analysis/new_analysis.py
> +def lucas(input_path, ref_method, output_directory="./5-results-lucas"):
Can you add a docstring to this function describing what it takes, what it does, etc.? You can use your notes from the PR and sculpt them into shape for here.

Same for the `swope` function.

2021-07-15 02:32 UTC, dotsdl commented on openff/benchmark/cli.py
> +@report.command()
Can you add docstrings for each of these four commands? See the other commands in the CLI for inspiration on how to structure this.

2021-07-22 20:26 UTC, closed without merging

2021-07-22 20:29 UTC, ldamore commented
Closed this PR since [PR#95](https://github.com/openforcefield/openff-benchmark/pull/95) resolved the points above.